
[Pantheon]
org_id = "23c7208e-5f2a-4388-9fc4-5c3a038ef8b9"

# $40 for each block of 10,000 Pantheon visitors
overage_block_size = 10000
overage_block_cost = 40.00

[Pantheon.plan_info]
# Use the spreadsheet at
# https://websites.umich.edu/~markmont/public/pantheon-cost-analysis
# to get the information to fill in below for your specific Pantheon
# subscription type and pricing.

[Pantheon.plan_info."Basic"]
upgrade_at    = 155000
upgrade_to    = "Performance Large"
downgrade_to  = "-"
traffic_limit = 35000
cost          = 500.00

[Pantheon.plan_info."Performance Small"]
upgrade_at    = 65000
upgrade_to    = "Performance Medium"
downgrade_to  = "-"
traffic_limit = 35000
cost          = 1925.00

[Pantheon.plan_info."Performance Medium"]
upgrade_at    = 140000
upgrade_to    = "Performance Large"
downgrade_to  = "Performance Small"
traffic_limit = 70000
cost          = 3300.00

[Pantheon.plan_info."Performance Large"]
upgrade_at    = 300000
upgrade_to    = "Performance Extra Large"
downgrade_to  = "Performance Medium"
traffic_limit = 210000
cost          = 6600.00

[Pantheon.plan_info."Performance Extra Large"]
upgrade_at    = 540000
upgrade_to    = "Performance 2X Large"
downgrade_to  = "Performance Large"
traffic_limit = 420000
cost          = 11000.00

[Pantheon.plan_info."Performance 2X Large"]
upgrade_at    = 1000000
upgrade_to    = "Elite 1M"
downgrade_to  = "Performance Extra Large"
traffic_limit = 840000
cost          = 16500.00

[Pantheon.plan_info."Elite 1M"]
upgrade_at    = 2000000
upgrade_to    = "Elite 2M"
downgrade_to  = "Performance 2X Large"
traffic_limit = 1000000
cost          = 99999.99

[Pantheon.plan_info."Elite 2M"]
upgrade_at    = 3000000
upgrade_to    = "-"
downgrade_to  = "Elite 1M"
traffic_limit = 2000000
cost          = 999999.99


[Pantheon.plan_sku_to_name]
# NOTE! The keys below will vary between Pantheon customers but changes to the values will be minimal.
plan-free-preferred-monthly-1              = "Sandbox"
plan-basic_small-contract-annual-1         = "Basic"
plan-performance_small-contract-annual-1   = "Performance Small"
plan-performance_medium-contract-annual-1  = "Performance Medium"
plan-performance_large-contract-annual-1   = "Performance Large"
plan-performance_xlarge-contract-annual-1  = "Performance Extra Large"
plan-performance_2xlarge-contract-annual-1 = "Performance 2X Large"
plan-elite_1m-contract-annual-1            = "Elite 1M"
plan-elite_2m-contract-annual-1            = "Elite 2M"


[Database]
# currently supported database types: sqlite, mysql

type = "sqlite"
name = "database.db"

#type = "mysql"
#host = "db-server.example.com"
#port = 3306
#user = "admin"
#password = "s3cr3t-p@sSW0rd!!"
#name = "sitehealth"


[Cloudflare]
enabled = false
# Values to use if the environnment variables CLOUDFLARE_EMAIL
# or CLOUDFLARE_API_KEY are not set.
member_email = "user@example.com"
member_api_key = "xxxxxxxx"


[AWS]
enabled = false
# Values to use if the environment variables AWS_PROFILE or
# AWS_DEFAULT_REGION are not set.
profile = "webhosting"
default_region = "us-east-1"
