[News.support-page-improvements]
order = "prepend"
icon =  '&#x1F4EC;'  # memorandum
message = '''
<h3 style="padding-top: 0;">U-M Pantheon support page improvements</h3>
<p>The page describing <a href="https://its.umich.edu/computing/web-mobile/pantheon/support">how to get support for U-M Pantheon</a> has been improved and expanded.  Check it out!</p>
'''
